par(mfrow=c(2,2))
plot(gr_d$dt, gr_d$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(gr_d$dt, gr_d$Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(gr_d$dt, gr_d$Sub_metering_1, type="n", xlab="", ylab="Energy sub metering")
lines(gr_d$dt, gr_d$Sub_metering_1, col="black")
lines(gr_d$dt, gr_d$Sub_metering_2, col="red")
lines(gr_d$dt, gr_d$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=1, col=c("black", "red", "blue"), cex=0.5, bty="n")
plot(gr_d$dt, gr_d$Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.print(png, file="plot4.png", width=480, height=480)
